// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msujdvczbmnhkfpjikwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdWpkdmN6Ym1uaGtmcGppa3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDIyNDgsImV4cCI6MjA2NDY3ODI0OH0.ONtSG1Hyd5nwUPb_MbFdQWrL9ATrAvJIl_X8HS_9cOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);